// Generated by CoffeeScript 1.6.3
(function () {
    var $agree = $("#agreeOpenHome");
    var $auto = $("#autoProxy");
    $agree.change(function () {
        var is_agree = $agree.is(":checked");
        console.log(is_agree);
        chrome.storage.local.set({lg_agree: is_agree});
    });

    $auto.change(function () {
        var is_auto = $auto.is(":checked");
        console.log(is_auto);
        chrome.storage.local.set({lg_auto: is_auto});
    });

    chrome.storage.local.get(["lg_agree", "lg_auto"], function (data) {
        if (data.lg_agree) {
            $agree.prop("checked", true);
        } else {
            $agree.prop("checked", false);
        }
        if (data.lg_auto) {
            $auto.prop("checked", true);
            $agree.prop("checked", true);   
        } else {
            $auto.prop("checked", false);

        }
    });


}).call(this);
